INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1000','1',13,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1001','1',5,'False');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1002','1',7,'False');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1003','1',10,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1004','1',12,'False');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1005','1',6,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1006','1',12,'False');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1007','1',5,'False');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1008','1',9,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1009','1',9,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1010','1',12,'False');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1011','1',8,'False');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1012','1',7,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1013','1',14,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1014','1',6,'False');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1015','1',6,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1016','1',9,'False');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1017','1',11,'False');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1018','1',15,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1019','1',6,'False');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1020','1',6,'False');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1021','1',13,'False');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1022','1',15,'False');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1023','1',10,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1024','1',11,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1025','1',7,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1026','1',12,'False');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1027','1',12,'False');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1028','1',7,'False');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1029','1',9,'False');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1030','1',5,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1031','1',10,'False');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1032','1',9,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1033','1',13,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1034','1',14,'False');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1035','1',15,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1036','1',12,'False');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1037','1',9,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1038','1',9,'False');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1039','1',5,'False');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1040','1',8,'False');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1041','1',11,'False');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1042','1',14,'False');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1043','1',8,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1044','1',7,'False');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1045','1',11,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1046','1',15,'False');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1047','1',13,'False');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1048','1',9,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1049','2',14,'False');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1050','2',13,'False');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1051','2',12,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1052','2',5,'False');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1053','2',11,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1054','2',14,'False');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1055','2',5,'False');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1056','2',7,'False');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1057','2',10,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1058','2',9,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1059','2',6,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1060','2',8,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1061','2',8,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1062','2',9,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1063','2',7,'False');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1064','2',8,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1065','2',13,'False');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1066','2',15,'False');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1067','2',5,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1068','2',7,'False');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1069','2',8,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1070','2',10,'False');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1071','2',8,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1072','2',5,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1073','2',11,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1074','2',8,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1075','2',14,'False');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1076','2',15,'False');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1077','2',10,'False');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1078','2',13,'False');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1079','2',15,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1080','2',13,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1081','2',14,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1082','2',12,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1083','2',8,'False');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1084','2',10,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1085','2',12,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1086','2',9,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1087','2',6,'False');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1088','2',5,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1089','3',12,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1090','3',6,'False');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1091','3',14,'False');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1092','3',8,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1093','3',11,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1094','3',11,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1095','3',7,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1096','3',9,'False');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1097','3',9,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1098','3',9,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1099','3',10,'False');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1100','3',13,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1101','3',13,'False');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1102','3',5,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1103','3',11,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1104','3',11,'False');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1105','3',13,'False');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1106','3',6,'False');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1107','3',10,'False');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1108','3',15,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1109','3',10,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1110','3',15,'False');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1111','3',12,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1112','3',14,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1113','3',10,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1114','3',14,'False');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1115','3',9,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1116','3',12,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1117','3',5,'False');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1118','3',8,'False');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1119','3',10,'False');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1120','3',8,'False');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1121','3',14,'False');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1122','3',10,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1123','3',9,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1124','3',14,'False');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1125','3',14,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1126','3',7,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1127','3',10,'False');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1128','3',15,'False');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1129','3',15,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1130','3',13,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1131','3',8,'False');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1132','3',15,'False');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1133','3',15,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1134','3',15,'False');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1135','3',15,'False');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1136','3',12,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1137','3',9,'False');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1138','3',12,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1139','4',14,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1140','4',11,'False');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1141','4',7,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1142','4',13,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1143','4',9,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1144','4',6,'False');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1145','4',10,'False');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1146','4',5,'False');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1147','4',13,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1148','4',12,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1149','4',5,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1150','4',7,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1151','5',5,'False');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1152','5',12,'False');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1153','5',14,'False');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1154','5',12,'False');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1155','5',15,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1156','5',12,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1157','5',5,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1158','5',7,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1159','5',11,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1160','5',5,'False');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1161','5',9,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1162','5',5,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1163','5',10,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1164','5',10,'False');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1165','5',11,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1166','5',15,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1167','5',7,'False');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1168','5',6,'False');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1169','5',15,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1170','5',5,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1171','5',11,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1172','5',14,'False');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1173','5',10,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1174','5',15,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1175','5',15,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1176','6',10,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1177','6',6,'False');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1178','6',14,'False');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1179','6',12,'False');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1180','6',12,'False');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1181','6',5,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1182','6',5,'False');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1183','6',9,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1184','6',14,'False');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1185','6',5,'False');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1186','6',13,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1187','6',13,'False');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1188','6',13,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1189','6',11,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1190','6',6,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1191','6',12,'False');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1192','6',14,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1193','7',14,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1194','7',5,'False');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1195','7',8,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1196','7',6,'False');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1197','7',11,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1198','7',6,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1199','7',8,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1200','7',12,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1201','7',8,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1202','7',14,'False');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1203','7',5,'False');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1204','7',12,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1205','7',14,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1206','7',11,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1207','7',9,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1208','7',15,'False');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1209','7',9,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1210','7',5,'False');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1211','7',5,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1212','7',9,'False');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1213','7',11,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1214','7',6,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1215','7',12,'False');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1216','7',8,'False');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1217','7',14,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1218','7',11,'False');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1219','7',13,'False');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1220','7',13,'False');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1221','7',13,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1222','7',15,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1223','7',9,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1224','7',8,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1225','7',5,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1226','8',7,'False');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1227','8',15,'False');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1228','8',9,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1229','8',9,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1230','8',11,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1231','8',9,'False');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1232','8',5,'False');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1233','8',10,'False');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1234','8',15,'False');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1235','8',11,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1236','8',11,'False');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1237','8',10,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1238','8',5,'False');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1239','8',12,'False');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1240','8',15,'False');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1241','8',14,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1242','8',14,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1243','8',10,'False');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1244','8',5,'False');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1245','8',7,'False');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1246','8',12,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1247','8',14,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1248','8',6,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1249','8',5,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1250','8',10,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1251','8',7,'False');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1252','8',6,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1253','8',13,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1254','8',9,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1255','8',11,'False');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1256','Línea 9',14,'False');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1257','Línea 9',12,'False');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1258','Línea 9',13,'False');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1259','Línea 9',12,'False');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1260','Línea 9',8,'False');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1261','Línea 9',9,'False');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1262','Línea 9',6,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1263','Línea 9',5,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1264','Línea 9',8,'False');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1265','Línea 9',8,'False');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1266','Línea 9',14,'False');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1267','Línea 9',5,'False');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1268','Línea 9',7,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1269','Línea 9',14,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1270','Línea 9',10,'False');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1271','Línea 9',13,'False');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1272','Línea 9',13,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1273','Línea 9',8,'False');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1274','Línea 9',13,'False');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1275','Línea 9',12,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1276','Línea 9',12,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1277','Línea 9',8,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1278','Línea 9',7,'False');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1279','Línea 9',8,'False');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1280','Línea 9',7,'False');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1281','Línea 9',9,'False');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1282','Línea 9',5,'False');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1283','Línea 9',5,'False');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1284','Línea 9',7,'False');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1285','Línea 12',14,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1286','Línea 12',15,'False');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1287','Línea 12',8,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1288','Línea 12',8,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1289','Línea 12',9,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1290','Línea 12',11,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1291','Línea 12',10,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1292','Línea 12',14,'False');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1293','Línea 12',14,'False');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1294','Línea 12',15,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1295','Línea 12',8,'False');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1296','Línea 12',15,'False');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1297','Línea 12',9,'False');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1298','Línea 12',14,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1299','Línea 12',7,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1300','Línea 12',9,'False');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1301','Línea 12',14,'False');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1302','Línea 12',6,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1303','Línea 12',8,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1304','Línea 12',11,'False');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1305','Línea 12',12,'False');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1306','Línea 12',14,'False');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1307','Línea 12',11,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1308','Línea 12',10,'False');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1309','Línea 12',6,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1310','Línea 12',9,'False');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1311','Línea 12',7,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1312','Línea 12',8,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1313','Línea 12',11,'False');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1314','Línea 12',6,'False');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1315','A',6,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1316','A',7,'False');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1317','A',9,'False');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1318','A',6,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1319','A',7,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1320','A',8,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1321','A',9,'False');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1322','A',9,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1323','A',8,'False');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1324','A',15,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1325','A',5,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1326','A',12,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1327','A',11,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1328','A',13,'False');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1329','A',11,'False');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1330','A',15,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1331','A',13,'False');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1332','A',15,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1333','A',13,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1334','A',6,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1335','A',12,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1336','A',8,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1337','A',14,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1338','A',8,'False');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1339','A',9,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1340','A',11,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1341','A',6,'False');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1342','A',15,'False');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1343','A',6,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1344','A',13,'False');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1345','A',5,'False');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1346','A',14,'False');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1347','A',11,'False');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1348','A',7,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1349','A',11,'False');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1350','A',8,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1351','A',8,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1352','A',6,'False');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1353','A',15,'False');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1354','B',6,'False');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1355','B',12,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1356','B',7,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1357','B',14,'False');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1358','B',11,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1359','B',9,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1360','B',9,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1361','B',8,'False');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1362','B',9,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1363','B',11,'False');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1364','B',7,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1365','B',13,'False');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1366','B',13,'False');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1367','B',14,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1368','B',7,'False');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1369','B',9,'False');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1370','B',15,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1371','B',8,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1372','B',11,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1373','B',10,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1374','B',11,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1375','B',14,'False');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1376','B',8,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1377','B',12,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1378','B',13,'False');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1379','B',13,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1380','B',12,'False');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1381','B',8,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1382','B',13,'False');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1383','B',6,'False');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1384','B',5,'False');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1385','B',10,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1386','B',12,'False');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1387','B',14,'False');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1388','B',13,'True');
INSERT INTO TABLE_NAME (Identificador,Línea Asignada,Número de Vagones,En Reparación) VALUES ('TREN-1389','B',12,'False');
